<!DOCTYPE html><html lang="zh-CN"><head><meta http-equiv="content-type" content="text/html; charset=utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="baidu-site-verification" content="codeva-WUJTOV7jES"><meta content="yes" name="apple-mobile-web-app-capable"><meta content="black-translucent" name="apple-mobile-web-app-status-bar-style"><meta content="telephone=no" name="format-detection"><meta name="description" content="深入分析了导致 ChatGPT 故障的 Redis 客户端 bug，异步命令被取消后，连接状态混乱，后续请求读取到错误数据。最终修复方案是遇到取消直接关闭连接，后续请求会重新建立连接，避免复用有问题的连接。文章梳理了bug的成因、复现、修复过程，也为开发者提供了调试异步连接问题的经验。"><title>解密 ChatGPT 数据泄露：Redis Bug 的深度分析</title><link rel="stylesheet" type="text/css" href="/css/normalize.min.css"><link rel="stylesheet" type="text/css" href="/css/pure-min.min.css"><link rel="stylesheet" type="text/css" href="/css/grids-responsive-min.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"><script type="text/javascript" src="/js/jquery.min.js"></script><link rel="stylesheet" type="text/css" href="/css/style.css?v=1.0.0"><link rel="icon" mask="" sizes="any" href="/favicon.ico"><link rel="Shortcut Icon" type="image/x-icon" href="/favicon.ico"><link rel="apple-touch-icon" href="/apple-touch-icon.png"><link rel="apple-touch-icon-precomposed" href="/apple-touch-icon.png"><link rel="alternate" type="application/atom+xml" href="/atom.xml"><script defer="" src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon="{&quot;token&quot;: &quot;973c5bad683a49b8af76df256779f523&quot;}"></script><script async="" src="https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script><meta name="referrer" content="no-referrer-when-downgrade"><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-QNFB9JLSPV"></script><script>window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-QNFB9JLSPV');
</script><script async="" type="text/javascript" src="/js/clipboard.min.js"></script><script async="" type="text/javascript" src="/js/toastr.min.js"></script><link rel="stylesheet" href="/css/toastr.min.css"><meta name="generator" content="Hexo 7.0.0"></head><body><div class="body_container"><div id="header"><div class="site-name"><h1 class="hidden">解密 ChatGPT 数据泄露：Redis Bug 的深度分析</h1><a id="logo" href="/.">Just For Fun</a><p class="description">知其然，知其所以然。知识广度是深度的副产品！</p></div><div id="nav-menu"><a class="current" href="/."><i class="fa fa-home"> 首页</i></a><a href="/archives/"><i class="fa fa-archive"> 归档</i></a><a href="/aboutme.html"><i class="fa fa-user"> 关于</i></a><a href="/links.html"><i class="fa fa-user-graduate"> 小盛律师</i></a><a href="/categories/%E6%B3%95%E5%BE%8B%E6%99%AE%E5%8F%8A/"><i class="fa fa-scale-balanced"> 法律普及</i></a><a href="/atom.xml"><i class="fa fa-rss"> 订阅</i></a></div></div><div class="pure-g" id="layout"><div class="pure-u-1 pure-u-md-3-4"><div class="content_container"><div class="post"><h1 class="post-title">解密 ChatGPT 数据泄露：Redis Bug 的深度分析</h1><div class="post-meta">2023/08/02<span> | </span><span class="category"><a href="/categories/%E6%BA%90%E7%A0%81%E5%89%96%E6%9E%90/">源码剖析</a></span><span id="busuanzi_container_page_pv"> | <span id="busuanzi_value_page_pv"></span><span> 阅读</span></span></div><a class="disqus-comment-count" data-disqus-identifier="2023/08/02/redis_python_bug/" href="/2023/08/02/redis_python_bug/#disqus_thread"></a><div class="post-content"><p>2023.03.20 号，OpenAI 的 ChatGPT 服务曾经中断了一段时间，随后 OpenAI 发了一篇公告 <a target="_blank" rel="noopener" href="https://openai.com/blog/march-20-chatgpt-outage">March 20 ChatGPT outage: Here’s what happened</a> 把这里的来龙去脉讲了一下。OpenAI 在公告里说明了本次故障的影响范围、补救策略、部分技术细节以及改进措施，还是很值得学习的。</p>
<p>本次事故处理的具体时间节点在 <a target="_blank" rel="noopener" href="https://status.openai.com/incidents/jq9232rcmktd">ChatGPT Web Interface Incident</a> 也有公开，如下图：</p>
<p><img src="https://slefboot-1251736664.file.myqcloud.com/20230726_redis_python_bug_incident.png/webp" alt="ChatGPT 故障整体修复时间节点" srcset="https://slefboot-1251736664.file.myqcloud.com/20230726_redis_python_bug_incident.png/webp 1444w, https://slefboot-1251736664.file.myqcloud.com/20230726_redis_python_bug_incident.png/webp400 400w, https://slefboot-1251736664.file.myqcloud.com/20230726_redis_python_bug_incident.png/webp800 800w" sizes="(min-width: 1150px) 723px, (min-width: 48em) calc((100vw - 120px) * 3 / 4 - 50px), (min-width: 35.5em) calc((100vw - 75px), calc(100vw - 40px)" width="1444" height="1108"></p>
<p>这个故障是由 Redis 的 Python 客户端 Bug 引发的，在 Github 上有关于这个 bug 的讨论。这个 bug 的修复过程并不顺利，有不少讨论和修复尝试，比如 <a target="_blank" rel="noopener" href="https://github.com/redis/redis-py/issues/2624">Issue 2624</a>，<a target="_blank" rel="noopener" href="https://github.com/redis/redis-py/pull/2641">PR 2641</a>，<a target="_blank" rel="noopener" href="https://github.com/redis/redis-py/issues/2665">Issue 2665</a>，<a target="_blank" rel="noopener" href="https://github.com/redis/redis-py/pull/2695">PR 2695</a>。看过这些后，似乎还是不能理解这里的修复，只好深入读读代码，看看这里的 bug 原因以及修复过程到底是怎么回事，顺便整理成这篇文章。</p>
<span id="more"></span>

<h2 id="故障公开"><a href="#故障公开" class="headerlink" title="故障公开"></a>故障公开</h2><p>在开始分析 Python 的 bug 之前，想先聊一下 OpenAI 的故障看板。OpenAI 提供有一个<a target="_blank" rel="noopener" href="https://status.openai.com/">故障状态查询页面</a>，可以在上面看到目前各个服务的健康状态。这点在国外做的比较好，很多服务都有 status 看板，比如 <a target="_blank" rel="noopener" href="https://www.githubstatus.com/">Github</a>，<a target="_blank" rel="noopener" href="https://status.cloud.google.com/">Google Cloud</a>。</p>
<p><img src="https://slefboot-1251736664.file.myqcloud.com/20230726_redis_python_bug_status.png/webp" alt="OpenAI status 看板，故障公示" srcset="https://slefboot-1251736664.file.myqcloud.com/20230726_redis_python_bug_status.png/webp 1806w, https://slefboot-1251736664.file.myqcloud.com/20230726_redis_python_bug_status.png/webp400 400w, https://slefboot-1251736664.file.myqcloud.com/20230726_redis_python_bug_status.png/webp800 800w, https://slefboot-1251736664.file.myqcloud.com/20230726_redis_python_bug_status.png/webp1600 1600w" sizes="(min-width: 1150px) 723px, (min-width: 48em) calc((100vw - 120px) * 3 / 4 - 50px), (min-width: 35.5em) calc((100vw - 75px), calc(100vw - 40px)" width="1806" height="1130"></p>
<p>当遇到 ChatGPT 不能用的时候，可以第一时间来这里看看当前服务状态。如果服务没问题，那一般就是自己的网络或者账户出了问题。一旦服务出问题，这里就能看到故障的进度。反观国内的很多服务，遇到问题是能遮掩就遮掩，就怕使用的人知道出故障。</p>
<p>本文的这个故障比较严重，OpenAI CEO <a target="_blank" rel="noopener" href="https://twitter.com/sama">Sam Altman</a> 也专门发了一个简短 <a target="_blank" rel="noopener" href="https://twitter.com/sama/status/1638635717462200320">说明</a>：</p>
<blockquote>
<p>we had a significant issue in ChatGPT due to a bug in an open source library, for which a fix has now been released and we have just finished validating.</p>
<p>a small percentage of users were able to see the titles of other users’ conversation history.</p>
<p>we feel awful about this.</p>
</blockquote>
<h3 id="故障详情"><a href="#故障详情" class="headerlink" title="故障详情"></a>故障详情</h3><p>OpenAI 官方随后写了一篇文章：<a target="_blank" rel="noopener" href="https://openai.com/blog/march-20-chatgpt-outage">March 20 ChatGPT outage: Here’s what happened</a> 详细介绍了本次故障。最开始是发现某些用户可以查看其他用户聊天对话中的标题，另外如果两个用户在同一时间活跃，那么新会话的第一条消息也可能会被其他人看到。后面又发现在特定的 9 个小时内，大概有 1.2% 左右的活跃 ChatGPT Plus 用户的支付信息被其他人看到。这里的支付信息包括：名字、电子邮件地址、付款地址、信用卡类型和信用卡号的<strong>最后四位数字</strong>以及信用卡到期日期。</p>
<p>当然这里支付信息被泄露的人数其实极少，因为触发条件比较苛刻，只有下面两种情况：</p>
<ol>
<li>在 2023.03.30 早上 1 点到 10 点打开了 OpenAI 发送的订阅确认邮件，邮件里可能有其他人的信用卡类型和卡号的后四位(好在没有完整卡号)。</li>
<li>在 2023.03.30 早上 1 点到 10 点在 ChatGPT 聊天页面点击“我的账户”，并且进入了“管理我的订阅”。这时候可能会看到其他 Plus 用户的名字和姓氏、电子邮件地址、付款地址、信用卡类型和信用卡号的最后四位数字（仅）以及信用卡到期日期。</li>
</ol>
<p>整个事故的处理时间节点在 <a target="_blank" rel="noopener" href="https://status.openai.com/incidents/jq9232rcmktd">ChatGPT Web Interface Incident</a> 有公开。</p>
<h3 id="故障原因"><a href="#故障原因" class="headerlink" title="故障原因"></a>故障原因</h3><p>OpenAI 给出了这个故障发生的一些技术细节：</p>
<ol>
<li>使用 Redis 缓存了用户的信息，避免每次都查询数据库。</li>
<li>Redis 是集群模式部署，负载分在许多个 Redis 实例上。</li>
<li>服务用 Python 开发，用到了异步I/O库 Asyncio，使用 redis-py 库来访问 Redis。</li>
<li>服务用 redis-py 库维护了一个到 Redis 集群的连接池，会复用连接来处理请求。</li>
<li>使用 Asyncio 异步处理 redis-py 的请求时，请求和响应可以看做两个队列，每个请求和响应在两个队列中是一一对应的。</li>
<li>如果请求已经入队到 Redis server，但在响应出队之前被取消，那么这个连接中请求和响应的对应关系会错乱。后面的请求可能会读到前面毫不相关的请求响应。</li>
<li>大多数情况下，因为读到的数据和请求预期不一致，会返回错误。</li>
<li>某些巧合情况下，读到的错误数据刚和和请求预期的数据类型一致，虽然不是同一个用户的信息，但是也会被正常显示。</li>
<li>在 2023.03.20 凌晨 1 点，进行服务变更后，redis 取消请求的调用量激增，导致出现了返回错误数据的情况(概率很低)；</li>
</ol>
<p>这里的关键在第 5 和第 6 点，后面我们会深入看看 redis-py 中这个 bug 的复现以及修复过程。</p>
<h3 id="故障处理"><a href="#故障处理" class="headerlink" title="故障处理"></a>故障处理</h3><p>OpenAI 对这个故障的处理措施也值得学习。首先是强调保护用户的隐私和数据安全，承认这次确实没做到，然后诚挚道歉，并发邮件通知了所有受影响的用户(不知道有没有啥实质的补偿)。</p>
<p>技术层面上，在找到了具体的原因后，也加固了这里的防护。具体来说就是：</p>
<ol>
<li>测试修复是否生效；</li>
<li>增加了数据的校验，保证请求和拿到的 Redis 缓存中的用户是同一个；</li>
<li>分析日志，保证消息不会被没权限的人看到；</li>
<li>通过多个数据源准确识别受影响的用户，然后进行通知；</li>
<li>增加了一些日志，确保问题被彻底解决，如果再出现这个问题，也能立马发现；</li>
<li>提高了 Redis 集群的鲁棒性，减少在极端负载情况下出现连接错误。</li>
</ol>
<p>接下来我们将聚焦 redis-py 的这个 bug，来看看如何复现并修复。</p>
<h2 id="Bug-复现"><a href="#Bug-复现" class="headerlink" title="Bug 复现"></a>Bug 复现</h2><p><a target="_blank" rel="noopener" href="https://github.com/drago-balto">drago-balto</a> 3.17 号在 <a target="_blank" rel="noopener" href="https://github.com/redis/redis-py">redis-py</a> 提交 <a target="_blank" rel="noopener" href="https://github.com/redis/redis-py/issues/2624">Issue 2624</a> 报告了 redis-py client 的这个 bug，简单说就是 <strong>Redis client 发出了一个异步请求，在收到并解析响应前，如果取消了这个异步请求，那么当前这个连接后续的命令就会出错</strong>。</p>
<blockquote>
<p>If async Redis request is canceled at the right time, after the command was sent but before the response was received and parsed, the connection is left in an unsafe state for future commands.</p>
</blockquote>
<p>要复现这里问题的话，先得有一个 redis server，可以在本地安装一个用默认配置启动就好。注意如果本地 redis 没有配置密码和 ssl 的话, redis 连接部分要改成注释的代码。然后用 <code>conda</code> 创建一个 python 的虚拟环境，安装 redis-py 的 4.5.1 版本 <code>pip install redis==4.5.1</code>。之后就可以用下面的脚本来复现 bug：</p>
<figure class="highlight python"><table><tbody><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> asyncio</span><br><span class="line"><span class="keyword">from</span> redis.asyncio <span class="keyword">import</span> Redis</span><br><span class="line"><span class="keyword">import</span> sys</span><br><span class="line"></span><br><span class="line"></span><br><span class="line"><span class="keyword">async</span> <span class="keyword">def</span> <span class="title function_">main</span>():</span><br><span class="line">    <span class="comment"># local redis server without passwd and ssl support</span></span><br><span class="line">    <span class="comment"># myhost = sys.argv[1]</span></span><br><span class="line">    <span class="comment"># async with Redis(host=myhost, ssl=False, single_connection_client=True) as r:</span></span><br><span class="line">    myhost, mypassword = sys.argv[<span class="number">1</span>:]</span><br><span class="line">    <span class="keyword">async</span> <span class="keyword">with</span> Redis(host=myhost, password=mypassword, ssl=<span class="literal">True</span>, single_connection_client=<span class="literal">True</span>) <span class="keyword">as</span> r:</span><br><span class="line"></span><br><span class="line">        <span class="keyword">await</span> r.<span class="built_in">set</span>(<span class="string">'foo'</span>, <span class="string">'foo'</span>)</span><br><span class="line">        <span class="keyword">await</span> r.<span class="built_in">set</span>(<span class="string">'bar'</span>, <span class="string">'bar'</span>)</span><br><span class="line"></span><br><span class="line">        t = asyncio.create_task(r.get(<span class="string">'foo'</span>))</span><br><span class="line">        <span class="keyword">await</span> asyncio.sleep(<span class="number">0.001</span>)</span><br><span class="line">        <span class="comment"># may change to some other value</span></span><br><span class="line">        <span class="comment"># await asyncio.sleep(0.000001)</span></span><br><span class="line">        t.cancel()</span><br><span class="line">        <span class="keyword">try</span>:</span><br><span class="line">            <span class="keyword">await</span> t</span><br><span class="line">            <span class="built_in">print</span>(<span class="string">'try again, we did not cancel the task in time'</span>)</span><br><span class="line">        <span class="keyword">except</span> asyncio.CancelledError:</span><br><span class="line">            <span class="built_in">print</span>(<span class="string">'managed to cancel the task, connection is left open with unread response'</span>)</span><br><span class="line"></span><br><span class="line">        <span class="built_in">print</span>(<span class="string">'bar:'</span>, <span class="keyword">await</span> r.get(<span class="string">'bar'</span>))</span><br><span class="line">        <span class="built_in">print</span>(<span class="string">'ping:'</span>, <span class="keyword">await</span> r.ping())</span><br><span class="line">        <span class="built_in">print</span>(<span class="string">'foo:'</span>, <span class="keyword">await</span> r.get(<span class="string">'foo'</span>))</span><br><span class="line"></span><br><span class="line"></span><br><span class="line"><span class="keyword">if</span> __name__ == <span class="string">'__main__'</span>:</span><br><span class="line">    asyncio.run(main())</span><br></pre></td></tr></tbody></table></figure>

<p>上面脚本用同一个 client 连接，先后执行了多个命令。其中异步执行 <code>r.get('foo')</code> 期间，调用 <code>cancel</code> 取消了这个查询，接着又执行了其他命令，通过观察后续命令的结果，就能知道这里有没有问题。注意这里在 <code>await t</code> 的时候，会尝试捕获异常 <code>asyncio.CancelledError</code>，如果捕获到这个异常，说明成功在 <code>r.get('foo')</code> 结束前取消了异步任务。如果没有异常，说明读 redis 任务已经完成，cancel 并没有成功取消异步任务。这里有个关键点就是 <code>asyncio.sleep(0.001)</code>，这里等待一段时间，就是为了让这个异步读请求被服务器接收并执行，但是在收到服务器的响应前被成功取消。</p>
<p>如果在Redis server 在云环境，延迟 &gt; 5ms，那么这里 <code>sleep(0.001)</code> 就能复现问题。我的 Redis client 和 server 都在一台机，网络耗时可以忽略。通过不断实验，发现这里 <code>asyncio.sleep(0.000001)</code> 能稳定复现，下面是在我本地，sleep 不同时间的执行结果：</p>
<p><img src="https://slefboot-1251736664.file.myqcloud.com/20230726_redis_python_bug_reproduce.png/webp" alt="Bug 的复现过程" srcset="https://slefboot-1251736664.file.myqcloud.com/20230726_redis_python_bug_reproduce.png/webp 2166w, https://slefboot-1251736664.file.myqcloud.com/20230726_redis_python_bug_reproduce.png/webp400 400w, https://slefboot-1251736664.file.myqcloud.com/20230726_redis_python_bug_reproduce.png/webp800 800w, https://slefboot-1251736664.file.myqcloud.com/20230726_redis_python_bug_reproduce.png/webp1600 1600w" sizes="(min-width: 1150px) 723px, (min-width: 48em) calc((100vw - 120px) * 3 / 4 - 50px), (min-width: 35.5em) calc((100vw - 75px), calc(100vw - 40px)" width="2166" height="700"></p>
<p>可以看到在 <code>sleep(0.000001)</code> 情况下，这里后续的 Redis 命令结果全部不对，每个命令都是上一个命令的结果。回到 OpenAI 的故障描述，就能解释为啥一个人看到了其他人的数据。因为这中间有取消的 redis 异步请求任务，导致结果错乱，读串了。</p>
<h2 id="源码剖析"><a href="#源码剖析" class="headerlink" title="源码剖析"></a>源码剖析</h2><p>之前没有怎么了解过 redis-py 的实现，为了快速定位这里的 bug 原因，最好的办法就是<strong>加日志</strong>。为了能够立即看到代码改动的效果，先把 redis-py 仓库 clone 到本地，然后用 <code>git checkout v4.5.1</code> 命令切换到 4.5.1 分支。接着用 conda 创建了一个新的虚拟环境，在这个新环境安装本地的库，这里用 <code>pip install -e .</code> ，带上 <code>-e</code> 后，本地的代码变更后就会立马生效。</p>
<p>官方的 redis-py 库写的还是比较清晰的，从 <a target="_blank" rel="noopener" href="https://github.com/redis/redis-py/blob/v4.5.1/redis/asyncio/client.py">client.py</a> 入手，能很快找到一些线索。比如 <code>execute_command</code> 函数，应该就是执行某个具体的命令，可以在 finally 的代码块里面加上日志 <code>print("execute_command finally", *args)</code> 来确认这一点。</p>
<h3 id="命令解析流程"><a href="#命令解析流程" class="headerlink" title="命令解析流程"></a>命令解析流程</h3><p>接下来比较关键的部分应该在 <code>_send_command_parse_response</code> 中了，可以看到首先发送命令，然后就是解析回包。</p>
<figure class="highlight python"><table><tbody><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">async</span> <span class="keyword">def</span> <span class="title function_">_send_command_parse_response</span>(<span class="params">self, conn, command_name, *args, **options</span>):</span><br><span class="line">    <span class="string">"""</span></span><br><span class="line"><span class="string">    Send a command and parse the response</span></span><br><span class="line"><span class="string">    """</span></span><br><span class="line">    <span class="keyword">await</span> conn.send_command(*args)</span><br><span class="line">    <span class="keyword">return</span> <span class="keyword">await</span> se</span><br><span class="line">    lf.parse_response(conn, command_name, **options)</span><br></pre></td></tr></tbody></table></figure>

<p>这里发送命令部分没啥问题，和我们的 bug 无关，可以跳过，主要来看解析回包部分了。直接看代码的话，干扰的因素太多了，各种分支比较难看的全。可以结合代码，同时不断的添加调试日志，整理一个请求的处理步骤。最后通过在 <code>_read_response</code> 里面打印函数堆栈，具体代码如下：</p>
<figure class="highlight python"><table><tbody><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">import</span> traceback</span><br><span class="line"><span class="built_in">print</span>(<span class="string">"_read_response"</span>, <span class="string">""</span>.join(traceback.format_stack()))</span><br></pre></td></tr></tbody></table></figure>

<p>通过堆栈，可以看到一个异步 redis get 请求的处理链路如下：</p>
<ol>
<li>blog_script/redis_bug.py (line 29) - <code>main</code></li>
<li>redis-py/redis/asyncio/client.py (line 514) - <code>execute_command</code></li>
<li>redis-py/redis/asyncio/retry.py (line 59) - <code>call_with_retry</code></li>
<li>redis-py/redis/asyncio/client.py (line 488) - <code>_send_command_parse_response</code></li>
<li>redis-py/redis/asyncio/client.py (line 535) - <code>parse_response</code></li>
<li>redis-py/redis/asyncio/connection.py (line 840) - <code>read_response</code></li>
<li>redis-py/redis/asyncio/connection.py (line 256) - <code>_parser.read_response</code></li>
<li>redis-py/redis/asyncio/connection.py (line 267) - <code>_read_response</code></li>
</ol>
<p>注意上面 <code>connection.py</code> 部分的行数可能和<a target="_blank" rel="noopener" href="https://github.com/redis/redis-py/tree/v4.5.1">实际代码</a>对不上，因为加了一些调试代码，影响了行数计算。取消异步任务，可以看到抛出了 <code>asyncio.CancelledError</code> 异常，那么具体是在哪里抛出这个异常呢？</p>
<h3 id="异常抛出位置"><a href="#异常抛出位置" class="headerlink" title="异常抛出位置"></a>异常抛出位置</h3><p>还是通过不断的加日志，定位到了 <a target="_blank" rel="noopener" href="https://github.com/redis/redis-py/blob/v4.5.1/redis/asyncio/connection.py#L341C12-L341C12">connection.py</a>，直观觉得应该在 <code>data = await self._stream.readline()</code> 中，这里的 <code>_stream</code> 是一个 <code>asyncio.StreamReader</code> 对象，它在读出一行内容的时候抛出了异常。如何确认这一点呢？尝试在这里添加 try 来捕获异常即可，不过开始的时候在这里捕获 <code>Exception</code> 异常，结果发现捕获不到。后来问了 ChatGPT，才知道在 Python 3.8 及更高版本中，<code>asyncio.CancelledError</code> 不再从 Exception 基类派生，而是直接从 <code>BaseException</code> 派生。于是改为下面的代码，验证了猜想。</p>
<figure class="highlight python"><table><tbody><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment"># redis/asyncio/connection.py</span></span><br><span class="line"><span class="keyword">async</span> <span class="keyword">def</span> <span class="title function_">_readline</span>(<span class="params">self</span>) -&gt; <span class="built_in">bytes</span>:</span><br><span class="line">    <span class="comment"># ...</span></span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        data = <span class="keyword">await</span> self._stream.readline()</span><br><span class="line">    <span class="comment"># 验证确实在这里抛出了异常</span></span><br><span class="line">    <span class="keyword">except</span> asyncio.CancelledError:</span><br><span class="line">        <span class="built_in">print</span>(<span class="string">"Task was cancelled"</span>)</span><br><span class="line">    <span class="comment"># ...</span></span><br></pre></td></tr></tbody></table></figure>

<h3 id="数据错乱原因"><a href="#数据错乱原因" class="headerlink" title="数据错乱原因"></a>数据错乱原因</h3><p>一个请求的执行流程已经很清晰了，但是还没有解决我们的疑问，<strong>为什么取消一个任务后，后续请求会读串</strong>。这里继续添加日志，在每个请求的开始部分打印请求命令( execute_command 里面添加日志)，然后打印解析出来的回包(_read_response 里面添加日志)，执行后结果如下：</p>
<p><img src="https://slefboot-1251736664.file.myqcloud.com/20230731_redis_python_bug_log.png/webp" alt="请求和回复的对应错乱了" srcset="https://slefboot-1251736664.file.myqcloud.com/20230731_redis_python_bug_log.png/webp 2290w, https://slefboot-1251736664.file.myqcloud.com/20230731_redis_python_bug_log.png/webp400 400w, https://slefboot-1251736664.file.myqcloud.com/20230731_redis_python_bug_log.png/webp800 800w, https://slefboot-1251736664.file.myqcloud.com/20230731_redis_python_bug_log.png/webp1600 1600w" sizes="(min-width: 1150px) 723px, (min-width: 48em) calc((100vw - 120px) * 3 / 4 - 50px), (min-width: 35.5em) calc((100vw - 75px), calc(100vw - 40px)" width="2290" height="722"></p>
<p>这里涉及到 Redis 回复的协议解析，Redis 使用的<code>RESP（Redis Serialization Protocol）</code>协议是一种简单、高效并且便于人直接阅读的基于文本的协议。它支持多种数据类型，包括字符串、数组和整数。客户端发送的命令请求和服务器的响应都遵循这个协议。具体格式的技术细节可以参考官方文档 <a target="_blank" rel="noopener" href="https://redis.io/docs/reference/protocol-spec/">RESP protocol spec</a>。</p>
<p>通过上面的截图可以看出来，这里 bug 的根本原因在于，<strong>如果异步请求成功被 server 处理，那么在 redline 读取出回复前就抛出了异常。后续的请求在调用 readline 的时候，会读到这个被取消请求的回复</strong>。</p>
<h2 id="Bug-修复"><a href="#Bug-修复" class="headerlink" title="Bug 修复"></a>Bug 修复</h2><p>对 Python 的异步库 asyncio 和 reids-py 的实现细节不是很清楚，所以这里就直接看官方的修复代码了。不过官方修复过程也不是很顺利，中间有的<strong>修复代码和测试代码都是有问题的</strong>，下面来看看。</p>
<h3 id="错误的修复方案"><a href="#错误的修复方案" class="headerlink" title="错误的修复方案"></a>错误的修复方案</h3><p>第一次修复尝试是在 <a target="_blank" rel="noopener" href="https://github.com/redis/redis-py/pull/2641">PR 2641</a> 中，有人提交了修复方案，关键部分在于：</p>
<p><img src="https://slefboot-1251736664.file.myqcloud.com/20230731_redis_python_bug_repair_error.png/webp" alt="修复的代码比对" srcset="https://slefboot-1251736664.file.myqcloud.com/20230731_redis_python_bug_repair_error.png/webp 3078w, https://slefboot-1251736664.file.myqcloud.com/20230731_redis_python_bug_repair_error.png/webp400 400w, https://slefboot-1251736664.file.myqcloud.com/20230731_redis_python_bug_repair_error.png/webp800 800w, https://slefboot-1251736664.file.myqcloud.com/20230731_redis_python_bug_repair_error.png/webp1600 1600w" sizes="(min-width: 1150px) 723px, (min-width: 48em) calc((100vw - 120px) * 3 / 4 - 50px), (min-width: 35.5em) calc((100vw - 75px), calc(100vw - 40px)" width="3078" height="778"></p>
<p>这里的核心思路在于，既然取消异步操作会导致漏读 server 的回复，那就保证一旦进入到读操作，就不允许取消异步任务(这里其实是一个协程)，直到读出这部分回复。这里用到了 <code>asyncio.shield</code> 函数，它用来<strong>保护一个异步操作不被取消</strong>。如果在 asyncio.shield 函数中的操作正在进行时，其他地方尝试取消这个操作，那么这个取消操作会被忽略，直到 asyncio.shield 函数中的操作完成再抛出异常。关于 asyncio.shield 的详细解释，可以参考官方文档 <a target="_blank" rel="noopener" href="https://docs.python.org/3/library/asyncio-task.html#shielding-from-cancellation">Shielding From Cancellation</a>。</p>
<p>这个修复方案被合并到了 <code>v4.5.3</code> 版本，然而在该版本下，能继续复现这个 bug。看了下代码，原因是这里的修复只对 <code>execute</code> 函数的取消加了保护，对于前面复现脚本执行路径中的 <code>execute_command</code> 并没有加保护。此外，这种保护方案本身也有问题，修改后就没法<strong>取消一个阻塞的异步请求</strong>，严重时甚至导致读请求卡住。</p>
<p>这个方案的提交者其实也提供了测试用例，不过用例写到有问题，导致没有测出这里的 bug。</p>
<p><img src="https://slefboot-1251736664.file.myqcloud.com/20230731_redis_python_bug_repair_error_test.png/webp" alt="错误的测试用例" srcset="https://slefboot-1251736664.file.myqcloud.com/20230731_redis_python_bug_repair_error_test.png/webp 1316w, https://slefboot-1251736664.file.myqcloud.com/20230731_redis_python_bug_repair_error_test.png/webp400 400w, https://slefboot-1251736664.file.myqcloud.com/20230731_redis_python_bug_repair_error_test.png/webp800 800w" sizes="(min-width: 1150px) 723px, (min-width: 48em) calc((100vw - 120px) * 3 / 4 - 50px), (min-width: 35.5em) calc((100vw - 75px), calc(100vw - 40px)" width="1316" height="790"></p>
<p>这里 <code>sleep</code> 的时间是 1s，这时候这个读请求早执行完了的，所以取消操作其实没生效。这里复现的一个关键点就在于，<strong>要卡一个很精确的时间点</strong>，保证请求被处理，但是回复内容还没被解析。这里引出一个重要问题，就是测试要如何卡这个时间点，让 bug 能在有问题的版本稳定复现。</p>
<h3 id="稳定复现与改进"><a href="#稳定复现与改进" class="headerlink" title="稳定复现与改进"></a>稳定复现与改进</h3><p>随后，有开发者起了一个新的 <a target="_blank" rel="noopener" href="https://github.com/redis/redis-py/issues/2665">Issue 2665</a>，来讨论这里如何<strong>稳定复现</strong>。做法很简单，起了一个 proxy server，来中转 client 和 server 的通信。中转的时候，不论是请求还是响应，都延迟 0.1s。这相当于伪造了一个通信延迟 0.1s 的网络环境，然后就能稳定控制 cancel 异步操作的时机了。</p>
<p>其中中转 proxy 的部分代码如下：</p>
<figure class="highlight python"><table><tbody><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">class</span> <span class="title class_">DelayProxy</span>:</span><br><span class="line"></span><br><span class="line">    <span class="keyword">def</span> <span class="title function_">__init__</span>(<span class="params">self, addr, redis_addr, delay: <span class="built_in">float</span></span>):</span><br><span class="line">        self.addr = addr</span><br><span class="line">        self.redis_addr = redis_addr</span><br><span class="line">        self.delay = delay</span><br><span class="line"></span><br><span class="line">    <span class="keyword">async</span> <span class="keyword">def</span> <span class="title function_">start</span>(<span class="params">self</span>):</span><br><span class="line">        server = <span class="keyword">await</span> asyncio.start_server(self.handle, *self.addr)</span><br><span class="line">        asyncio.create_task(server.serve_forever())</span><br><span class="line"></span><br><span class="line">    <span class="keyword">async</span> <span class="keyword">def</span> <span class="title function_">handle</span>(<span class="params">self, reader, writer</span>):</span><br><span class="line">        <span class="comment"># establish connection to redis</span></span><br><span class="line">        redis_reader, redis_writer = <span class="keyword">await</span> asyncio.open_connection(*self.redis_addr)</span><br><span class="line">        pipe1 = asyncio.create_task(pipe(reader, redis_writer, self.delay, <span class="string">'to redis:'</span>))</span><br><span class="line">        pipe2 = asyncio.create_task(pipe(redis_reader, writer, self.delay, <span class="string">'from redis:'</span>))</span><br><span class="line">        <span class="keyword">await</span> asyncio.gather(pipe1, pipe2)</span><br></pre></td></tr></tbody></table></figure>

<p>完整的复现代码见 <a target="_blank" rel="noopener" href="https://gist.github.com/selfboot/9cb19090008d0d560f22fba31e82c2cc">redis_cancel.py</a>。</p>
<p>针对这里的复现，chayim 接着提交了 <a target="_blank" rel="noopener" href="https://github.com/redis/redis-py/pull/2666">PR 2666</a> 中，对应 commit <a target="_blank" rel="noopener" href="https://github.com/redis/redis-py/commit/5acbde355058ab7d9c2f95bcef3993ab4134e342">5acbde3</a> 被放在 v4.5.4，在所有的命令操作场景中都用 <code>asyncio.shield</code> 禁止取消操作，关键部分的改动如下：</p>
<p><img src="https://slefboot-1251736664.file.myqcloud.com/20230802_redis_python_bug_shield_everywhere.png/webp" alt="asyncio.shield 加保护" srcset="https://slefboot-1251736664.file.myqcloud.com/20230802_redis_python_bug_shield_everywhere.png/webp 3048w, https://slefboot-1251736664.file.myqcloud.com/20230802_redis_python_bug_shield_everywhere.png/webp400 400w, https://slefboot-1251736664.file.myqcloud.com/20230802_redis_python_bug_shield_everywhere.png/webp800 800w, https://slefboot-1251736664.file.myqcloud.com/20230802_redis_python_bug_shield_everywhere.png/webp1600 1600w" sizes="(min-width: 1150px) 723px, (min-width: 48em) calc((100vw - 120px) * 3 / 4 - 50px), (min-width: 35.5em) calc((100vw - 75px), calc(100vw - 40px)" width="3048" height="1260"></p>
<p>相当于对前面修复的一个补丁，这样确实修复了读串数据的 bug，新的测试脚本也无法复现。我们对下面的修复代码稍作改动，就能更好理解这里的修复原理了。把代码中的 <code>asyncio.shield</code> 部分抽离出来，打印结果，并尝试捕获异常。改动部分如下：</p>
<figure class="highlight python"><table><tbody><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">async</span> <span class="keyword">def</span> <span class="title function_">execute_command</span>(<span class="params">self, *args, **options</span>):</span><br><span class="line">    <span class="comment"># ...</span></span><br><span class="line">    result = <span class="literal">None</span></span><br><span class="line">    <span class="keyword">try</span>: </span><br><span class="line">        result = <span class="keyword">await</span> asyncio.shield(</span><br><span class="line">            self._try_send_command_parse_response(conn, *args, **options)</span><br><span class="line">        )</span><br><span class="line">        <span class="built_in">print</span>(<span class="string">f"[log] <span class="subst">{args}</span> <span class="subst">{result}</span>"</span>)</span><br><span class="line">        <span class="keyword">return</span> result</span><br><span class="line">    <span class="keyword">except</span> asyncio.CancelledError:</span><br><span class="line">        <span class="built_in">print</span>(<span class="string">f"[EXCEPTION] <span class="subst">{args}</span>"</span>)</span><br></pre></td></tr></tbody></table></figure>

<p>重新执行测试脚本，就能看到对于取消异步读部分的请求，输出如下：</p>
<blockquote>
<p>[EXCEPTION] (‘GET’, ‘foo’)<br>try again, we did not cancel the task in time</p>
</blockquote>
<p>可以看到加了 <code>asyncio.shield</code> 后，异步任务并没有在原来的 <code>data = await self._stream.readline()</code>(见前面对这里的说明) 位置抛出异常，而是正常执行完了异步的 get 操作，拿到结果 ‘foo’ 后在 <code>await asyncio.shield</code> 这里才最终抛出 asyncio.CancelledError 异常。本次 PR 还提交了能稳定复现的测试用例，在 <a target="_blank" rel="noopener" href="https://github.com/redis/redis-py/pull/2666/files#diff-a90c3a19dad7803c9726358f223a3b7b8fb23ccb1d573d580d6640f04fdd3f27">tests/test_asyncio/test_cwe_404.py</a> 中，基本思想还是用代理模拟延迟时间。</p>
<h3 id="背景与最终修复"><a href="#背景与最终修复" class="headerlink" title="背景与最终修复"></a>背景与最终修复</h3><p>上面的修复看似解决了问题，不过 <a target="_blank" rel="noopener" href="https://github.com/kristjanvalur">kristjanvalur</a> 对这个修复方案很不满意，在 <a target="_blank" rel="noopener" href="https://github.com/redis/redis-py/pull/2666">PR 2666</a> 中也直接跟贴评论了。其实前面也提过，这种延迟异常抛出的做法，导致没法真正取消一个异步请求，在某些场景下甚至导致死锁。kristjanvalur 在这个 PR 中也给出了一个示例代码，来证明完全有可能导致死锁问题。</p>
<p>好事做到底，kristjanvalur 接着提了一个新的 <a target="_blank" rel="noopener" href="https://github.com/redis/redis-py/pull/2695">PR 2695</a>。这个 PR 的内容比较多，包括回滚 <code>v4.5.3</code> 和 <code>4.5.4</code> 中 shield 相关的代码，然后修复导致 ChatGPT 读错数据的的 <a target="_blank" rel="noopener" href="https://github.com/redis/redis-py/issues/2624">Issue 2624</a>，并提供了一个单元测试。</p>
<p>再多说一点这里的背景，kristjanvalur 2022年就为 <code>asyncio/client.py</code> 贡献了很多代码，包括 <a target="_blank" rel="noopener" href="https://github.com/redis/redis-py/pull/2104">PR 2104: Catch Exception and not BaseException in the Connection</a>，也就是只有遇到 Exception 情况才会关闭连接。正是这个改动，导致了某些场景下包含错误数据的连接，会被放回去连接池，具体讨论可以看 <a target="_blank" rel="noopener" href="https://github.com/redis/redis-py/issues/2499">Issue 2499: BaseException at I/O corrupts Connection</a>，这次的 bug 也是这个改动带来的。</p>
<p>具体修复方案的核心代码如下，在 <a target="_blank" rel="noopener" href="https://github.com/redis/redis-py/blob/f056118224e851915922de02ec40f2d16c9e4dd7/redis/asyncio/connection.py#L831C15-L831C28">read_response</a> 中增加了对 BaseException 的异常处理，默认是直接断开连接。</p>
<p><img src="https://slefboot-1251736664.file.myqcloud.com/20230802_redis_python_bug_disconnect.png/webp" alt="异常直接断开连接" srcset="https://slefboot-1251736664.file.myqcloud.com/20230802_redis_python_bug_disconnect.png/webp 3212w, https://slefboot-1251736664.file.myqcloud.com/20230802_redis_python_bug_disconnect.png/webp400 400w, https://slefboot-1251736664.file.myqcloud.com/20230802_redis_python_bug_disconnect.png/webp800 800w, https://slefboot-1251736664.file.myqcloud.com/20230802_redis_python_bug_disconnect.png/webp1600 1600w" sizes="(min-width: 1150px) 723px, (min-width: 48em) calc((100vw - 120px) * 3 / 4 - 50px), (min-width: 35.5em) calc((100vw - 75px), calc(100vw - 40px)" width="3212" height="1348"></p>
<h3 id="最终的验证过程"><a href="#最终的验证过程" class="headerlink" title="最终的验证过程"></a>最终的验证过程</h3><p>根据 <a target="_blank" rel="noopener" href="https://github.com/redis/redis-py/releases">Release</a> 页面的版本日志，可以看到 4.5.5 版本合并了 PR 2695，如下图：</p>
<p><img src="https://slefboot-1251736664.file.myqcloud.com/20230728_redis_python_bug_release.png/webp" alt="Redis python 的修复记录" srcset="https://slefboot-1251736664.file.myqcloud.com/20230728_redis_python_bug_release.png/webp 1884w, https://slefboot-1251736664.file.myqcloud.com/20230728_redis_python_bug_release.png/webp400 400w, https://slefboot-1251736664.file.myqcloud.com/20230728_redis_python_bug_release.png/webp800 800w, https://slefboot-1251736664.file.myqcloud.com/20230728_redis_python_bug_release.png/webp1600 1600w" sizes="(min-width: 1150px) 723px, (min-width: 48em) calc((100vw - 120px) * 3 / 4 - 50px), (min-width: 35.5em) calc((100vw - 75px), calc(100vw - 40px)" width="1884" height="1406"></p>
<p>切换到 <code>v4.5.5</code> 分支，然后再次用上面的复现脚本尝试验证，得到结果如下：</p>
<p><img src="https://slefboot-1251736664.file.myqcloud.com/20230731_redis_python_bug_log_succ.png/webp" alt="已经修复好的输出" srcset="https://slefboot-1251736664.file.myqcloud.com/20230731_redis_python_bug_log_succ.png/webp 2058w, https://slefboot-1251736664.file.myqcloud.com/20230731_redis_python_bug_log_succ.png/webp400 400w, https://slefboot-1251736664.file.myqcloud.com/20230731_redis_python_bug_log_succ.png/webp800 800w, https://slefboot-1251736664.file.myqcloud.com/20230731_redis_python_bug_log_succ.png/webp1600 1600w" sizes="(min-width: 1150px) 723px, (min-width: 48em) calc((100vw - 120px) * 3 / 4 - 50px), (min-width: 35.5em) calc((100vw - 75px), calc(100vw - 40px)" width="2058" height="730"></p>
<p>至此，这个 bug 彻底修复了。再来加日志对上面的理解过程做一些验证，比如：</p>
<ol>
<li>取消任务的时候，这里会断开连接；</li>
<li>下一次拿连接的时候，会用到一个新的连接；</li>
</ol>
<p>这里在准备断开连接和新建连接的地方加上日志，通过 <code>id(self._reader)</code> 来验证确实建了新的 <code>asyncio.StreamReader</code> 对象。 如下：</p>
<figure class="highlight python"><table><tbody><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line">--- a/redis/asyncio/connection.py</span><br><span class="line">+++ b/redis/asyncio/connection.py</span><br><span class="line"><span class="meta">@@ -<span class="number">638</span>,<span class="number">6</span> +<span class="number">638</span>,<span class="number">8</span> @@ class Connection:</span></span><br><span class="line">             task = callback(self)</span><br><span class="line">             <span class="keyword">if</span> task <span class="keyword">and</span> inspect.isawaitable(task):</span><br><span class="line">                 <span class="keyword">await</span> task</span><br><span class="line">+</span><br><span class="line">+        <span class="built_in">print</span>(<span class="string">f'[log] New Connection <span class="subst">{<span class="built_in">id</span>(self._reader)}</span> <span class="subst">{<span class="built_in">id</span>(self._writer)}</span>'</span>)</span><br><span class="line"></span><br><span class="line">     <span class="keyword">async</span> <span class="keyword">def</span> <span class="title function_">_connect</span>(<span class="params">self</span>):</span><br><span class="line">         <span class="string">"""Create a TCP socket connection"""</span></span><br><span class="line"><span class="meta">@@ -<span class="number">866</span>,<span class="number">6</span> +<span class="number">868</span>,<span class="number">7</span> @@ class Connection:</span></span><br><span class="line">             <span class="comment"># relies on this behaviour when doing Command/Response pairs.</span></span><br><span class="line">             <span class="comment"># See #1128.</span></span><br><span class="line">             <span class="keyword">if</span> disconnect_on_error:</span><br><span class="line">+                <span class="built_in">print</span>(<span class="string">f'[log] disconnecting <span class="subst">{<span class="built_in">id</span>(self._reader)}</span> <span class="subst">{<span class="built_in">id</span>(self._writer)}</span>'</span>)</span><br><span class="line">                 <span class="keyword">await</span> self.disconnect(nowait=<span class="literal">True</span>)</span><br><span class="line">             <span class="keyword">raise</span></span><br></pre></td></tr></tbody></table></figure>

<p>得到的输出如下，可以看到在取消任务时，立马断开了连接，这时候 id=4388303056 的 stream read 被销毁。接下来的 redis 操作新创建了 connection，并且分配了新的 id=4388321104 的 stream read。</p>
<blockquote>
<p>[log] New Connection 4388303056 4385849616<br>[log] disconnecting 4388303056 4385849616<br>managed to cancel the task, connection is left open with unread response<br>[log] New Connection 4388321104 4385849616<br>bar: b’bar’<br>ping: True<br>foo: b’foo’</p>
</blockquote>
<p>整体的修复思路清晰了，就是对于异常的请求 client，直接关闭 connection，这样会清理读写流。下一次再有新的请求，用一个新的流，就不会有读乱的问题了。</p>
<h2 id="简单总结"><a href="#简单总结" class="headerlink" title="简单总结"></a>简单总结</h2><p>OpenAI 公开了一个<strong>故障状态页面</strong>，实时展示各项服务的运行情况。当 ChatGPT 不可用时，用户可以第一时间在状态页面上确认，而不是盲目猜测问题出在自己这边。这种高透明度的做法值得学习，首先它体现了对用户的尊重和负责，不轻易封锁消息。其次也有利于公司积极主动应对问题，而不是回避或隐瞒。</p>
<p>OpenAI <strong>公布的技术细节</strong>相当翔实，这也体现了其高度透明的态度。报告中还特别说明了问题仅存在于非常短的窗口，并列出了各种补救和防范措施，包括新增校验逻辑、日志记录、提升容错性等。这些细节无不显示 OpenAI 对用户隐私和产品质量的高度重视。然后通过详细分析本次 ChatGPT 服务中断的技术原因，我们也可以获得以下启示:</p>
<p>首先，这充分说明了开源社区力量的伟大。从最初的问题报告，到错误修复方案的提交，再到提供稳定复现手段，以及最终合理修复方案的实现，整个过程都有开源社区参与者的贡献。正是因为这样的协作，一个严重的 bug 才能在短时间内系统性地被分析并修复。</p>
<p>其次，这也体现了定位难以稳定复现的 bug 需要技巧。使用代理服务器来模拟网络延迟，创造出错误触发的时机窗口,为确认和定位 bug 提供了重要支持。这种手段对处理各类偶发的异常问题具有借鉴意义。</p>
<p>另外，这也展示了异步编程的难点。理解一个异步任务流的执行需要对代码细节有非常强的把握。打印日志和添加断点是必要手段，同时需要对语言和库的行为有充分理解，才能分析出问题的根源所在。</p>
<p>最后，这个案例也彰显了优秀开源项目的价值。不仅要提供可靠的功能实现，还需要有完善的文档、注释和测试代码。这是开源项目能够长期发展的基石。读者可以通过这种源码级的调试分析，掌握定位难点问题的技巧，提高自己的编程能力。也希望本文对需要深入理解开源项目实现的读者有所启发和帮助。</p>
<blockquote>
<p>最后总结部分是 claude2 写的，感觉还可以？虽然有点说教的感觉。</p>
</blockquote>
</div><div class="article-footer-copyright"><p>本文由<b>selfboot</b> 发表于<a href="https://selfboot.cn" target="_blank">个人博客</a>，采用<a href="https://creativecommons.org/licenses/by-sa/3.0/cn/" target="_blank">署名-非商业性使用-相同方式共享 3.0 中国大陆许可协议。</a></p><p>本文章已自动同步在<b style="color:red">个人公众号</b>，欢迎去 <a href="https://selfboot.cn/aboutme.html" target="_blank">个人主页 </a> 扫码关注</p><p>非商业转载请注明作者及出处。商业转载请联系<a href="mailto:xuezaigds@gmail.com">作者本人</a></p><p>本文标题为：解密 ChatGPT 数据泄露：Redis Bug 的深度分析</p><p>本文链接为：https://selfboot.cn/2023/08/02/redis_python_bug/</p></div><div class="post-donate"><div class="donate_bar center" id="donate_board"><a class="btn_donate" id="btn_donate" href="javascript:;" title="打赏"></a><div class="donate_txt"> ↑<br>内容不错，打赏你啦<br></div></div><div class="donate_bar center hidden" id="donate_guide"><img src="https://slefboot-1251736664.file.myqcloud.com/weixin.jpg" title="微信打赏"><img src="https://slefboot-1251736664.file.myqcloud.com/zhifubao.jpg" title="支付宝打赏"></div><script type="text/javascript">document.getElementById('btn_donate').onclick = function(){
    $('#donate_board').addClass('hidden');
    $('#donate_guide').removeClass('hidden');
}</script></div><div class="addthis_sharing_toolbox"></div><div class="tags"><a href="/tags/Python/"><i class="fa fa-tag"></i>Python</a><a href="/tags/ChatGPT/"><i class="fa fa-tag"></i>ChatGPT</a><a href="/tags/Redis/"><i class="fa fa-tag"></i>Redis</a></div><div class="post-nav"><a class="pre" href="/2023/08/05/divorce_legal_longtime/">离婚法律指南：离婚流程要多久？</a><a class="next" href="/2023/07/29/divorce_legal_money_parent/">离婚财产分割：父母给的首付钱如何分？</a></div><div id="disqus_thread"><div class="btn_click_load"><button class="disqus_click_btn">阅读评论（请确保 Disqus 可以正常加载）</button></div><script type="text/javascript">var disqus_config = function () {
    this.page.url = 'https://selfboot.cn/2023/08/02/redis_python_bug/';
    this.page.identifier = '2023/08/02/redis_python_bug/';
    this.page.title = '解密 ChatGPT 数据泄露：Redis Bug 的深度分析';
  };</script><script type="text/javascript" id="disqus-lazy-load-script">$.ajax({
url: 'https://disqus.com/next/config.json',
timeout: 2500,
type: 'GET',
success: function(){
  var d = document;
  var s = d.createElement('script');
  s.src = '//xuelangZF.disqus.com/embed.js';
  s.setAttribute('data-timestamp', + new Date());
  (d.head || d.body).appendChild(s);
  $('.disqus_click_btn').css('display', 'none');
},
error: function() {
  $('.disqus_click_btn').css('display', 'block');
}
});</script><script type="text/javascript" id="disqus-click-load">$('.btn_click_load').click(() => {  //click to load comments
    (() => { // DON'T EDIT BELOW THIS LINE
        var d = document;
        var s = d.createElement('script');
        s.src = '//xuelangZF.disqus.com/embed.js';
        s.setAttribute('data-timestamp', + new Date());
        (d.head || d.body).appendChild(s);
    })();
    $('.disqus_click_btn').css('display','none');
});</script><script type="text/javascript" id="disqus-count-script">$(function() {
     var xhr = new XMLHttpRequest();
     xhr.open('GET', '//disqus.com/next/config.json', true);
     xhr.timeout = 2500;
     xhr.onreadystatechange = function () {
       if (xhr.readyState === 4 && xhr.status === 200) {
         $('.post-meta .post-comments-count').show();
         var s = document.createElement('script');
         s.id = 'dsq-count-scr';
         s.src = 'https://xuelangZF.disqus.com/count.js';
         s.async = true;
         (document.head || document.body).appendChild(s);
       }
     };
     xhr.ontimeout = function () { xhr.abort(); };
     xhr.send(null);
   });
</script></div></div></div></div><div class="pure-u-1-4 hidden_mid_and_down"><div id="sidebar"><div class="widget"><form class="search-form" action="https://www.google.com/search" method="get" accept-charset="utf-8" target="_blank"><input type="text" name="q" maxlength="20" placeholder="Search"><input type="hidden" name="sitesearch" value="https://selfboot.cn"></form></div><div class="widget"><div class="widget-title"><i class="fa fa-folder-o"> 分类</i></div><ul class="category-list"><li class="category-list-item"><a class="category-list-link" href="/categories/%E4%BA%BA%E5%B7%A5%E6%99%BA%E8%83%BD/">人工智能</a><span class="category-list-count">28</span></li><li class="category-list-item"><a class="category-list-link" href="/categories/%E5%B7%A5%E5%85%B7%E4%BB%8B%E7%BB%8D/">工具介绍</a><span class="category-list-count">13</span></li><li class="category-list-item"><a class="category-list-link" href="/categories/%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84%E4%B8%8E%E7%AE%97%E6%B3%95/">数据结构与算法</a><span class="category-list-count">13</span></li><li class="category-list-item"><a class="category-list-link" href="/categories/%E6%B3%95%E5%BE%8B%E6%99%AE%E5%8F%8A/">法律普及</a><span class="category-list-count">22</span></li><li class="category-list-item"><a class="category-list-link" href="/categories/%E6%BA%90%E7%A0%81%E5%89%96%E6%9E%90/">源码剖析</a><span class="category-list-count">5</span></li><li class="category-list-item"><a class="category-list-link" href="/categories/%E7%A4%BE%E4%BC%9A%E7%99%BE%E6%80%81/">社会百态</a><span class="category-list-count">11</span></li><li class="category-list-item"><a class="category-list-link" href="/categories/%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1/">程序设计</a><span class="category-list-count">20</span></li><li class="category-list-item"><a class="category-list-link" href="/categories/%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/">计算机基础</a><span class="category-list-count">8</span></li><li class="category-list-item"><a class="category-list-link" href="/categories/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%BD%91%E7%BB%9C/">计算机网络</a><span class="category-list-count">4</span></li><li class="category-list-item"><a class="category-list-link" href="/categories/%E9%87%91%E8%9E%8D/">金融</a><span class="category-list-count">1</span></li><li class="category-list-item"><a class="category-list-link" href="/categories/%E9%A1%B9%E7%9B%AE%E5%AE%9E%E8%B7%B5/">项目实践</a><span class="category-list-count">9</span></li></ul></div><div class="widget"><div class="widget-title"><i class="fa fa-star-o"> 标签</i></div><div class="tagcloud"><a href="/tags/Python/" style="font-size: 15px;">Python</a> <a href="/tags/%E6%95%99%E7%A8%8B/" style="font-size: 15px;">教程</a> <a href="/tags/%E6%80%BB%E7%BB%93/" style="font-size: 15px;">总结</a> <a href="/tags/%E6%96%B9%E6%B3%95/" style="font-size: 15px;">方法</a> <a href="/tags/Google/" style="font-size: 15px;">Google</a> <a href="/tags/%E6%80%9D%E8%80%83/" style="font-size: 15px;">思考</a> <a href="/tags/%E5%89%8D%E7%AB%AF/" style="font-size: 15px;">前端</a> <a href="/tags/Django/" style="font-size: 15px;">Django</a> <a href="/tags/DNS/" style="font-size: 15px;">DNS</a> <a href="/tags/%E8%A7%81%E9%97%BB/" style="font-size: 15px;">见闻</a> <a href="/tags/Protocol/" style="font-size: 15px;">Protocol</a> <a href="/tags/C/" style="font-size: 15px;">C++</a> <a href="/tags/Flask/" style="font-size: 15px;">Flask</a> <a href="/tags/Thread/" style="font-size: 15px;">Thread</a> <a href="/tags/%E6%B3%95%E5%BE%8B/" style="font-size: 15px;">法律</a> <a href="/tags/ChatGPT/" style="font-size: 15px;">ChatGPT</a> <a href="/tags/Prompt/" style="font-size: 15px;">Prompt</a> <a href="/tags/Plugin/" style="font-size: 15px;">Plugin</a> <a href="/tags/Leetcode/" style="font-size: 15px;">Leetcode</a> <a href="/tags/Redis/" style="font-size: 15px;">Redis</a> <a href="/tags/Debug/" style="font-size: 15px;">Debug</a> <a href="/tags/Issue/" style="font-size: 15px;">Issue</a> <a href="/tags/eBPF/" style="font-size: 15px;">eBPF</a> <a href="/tags/%E5%A9%9A%E5%A7%BB%E5%AE%B6%E5%BA%AD/" style="font-size: 15px;">婚姻家庭</a> <a href="/tags/Go/" style="font-size: 15px;">Go</a> <a href="/tags/%E5%88%91%E4%BA%8B/" style="font-size: 15px;">刑事</a> <a href="/tags/%E5%8A%B3%E5%8A%A8%E7%BA%A0%E7%BA%B7/" style="font-size: 15px;">劳动纠纷</a> <a href="/tags/%E6%95%B0%E5%AD%A6/" style="font-size: 15px;">数学</a> <a href="/tags/Gemini/" style="font-size: 15px;">Gemini</a> <a href="/tags/google/" style="font-size: 15px;">google</a></div></div><!-- Debug: page.path = 2023/08/02/redis_python_bug/ --><div class="widget"><div class="widget-title"><i class="fa fa-file-o"> 最近文章</i></div><ul><li><a href="/2024/03/15/object_memory_coredump/" title="Bazel 依赖缺失导致的 C++ 进程 coredump 问题分析">Bazel 依赖缺失导致的 C++ 进程 coredump 问题分析</a></li><li><a href="/2024/01/25/why_need_use_gpt_asap/" title="为什么一定要尽快用上 ChatGPT 等大语言模型">为什么一定要尽快用上 ChatGPT 等大语言模型</a></li><li><a href="/2024/01/18/supply_chain_attack_on_pytorch/" title="我们是如何对 PyTorch 发起供应链攻击的 (译文)">我们是如何对 PyTorch 发起供应链攻击的 (译文)</a></li><li><a href="/2024/01/17/c++_string_cow/" title="C++ string 意外修改之深入理解 COW 写时复制">C++ string 意外修改之深入理解 COW 写时复制</a></li><li><a href="/2024/01/09/openai_python_sdk_learn/" title="跟 OpenAI 学写 ChatGPT API 的 Python SDK 库">跟 OpenAI 学写 ChatGPT API 的 Python SDK 库</a></li><li><a href="/2024/01/03/hexo_blog_speed/" title="个人博客访问速度优化：CDN, 图片压缩, HTTP2">个人博客访问速度优化：CDN, 图片压缩, HTTP2</a></li><li><a href="/2023/12/28/black_hat_SEO/" title="从外围引流贴看黑产的搜索引擎排名优化生意">从外围引流贴看黑产的搜索引擎排名优化生意</a></li><li><a href="/2023/12/25/how-to-use-chatgpt/" title="安全、快速、便宜访问 ChatGPT，最新最全实践教程！">安全、快速、便宜访问 ChatGPT，最新最全实践教程！</a></li><li><a href="/2023/12/10/google-gemini-bard-hands-on/" title="Google Gemini Pro 深度体验，离 GPT4 还有多大差距？">Google Gemini Pro 深度体验，离 GPT4 还有多大差距？</a></li><li><a href="/2023/12/06/bert_nlp_classify/" title="零基础用 Bert 训练并部署文本分类模型">零基础用 Bert 训练并部署文本分类模型</a></li></ul></div><div class="widget" id="toc"><div class="widget-title"><i class="fa fa-list-ul"> 文章目录</i></div><ul class="dsq-widget-list"><ol class="toc"><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%95%85%E9%9A%9C%E5%85%AC%E5%BC%80"><span class="toc-number">1.</span> <span class="toc-text">故障公开</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#%E6%95%85%E9%9A%9C%E8%AF%A6%E6%83%85"><span class="toc-number">1.1.</span> <span class="toc-text">故障详情</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E6%95%85%E9%9A%9C%E5%8E%9F%E5%9B%A0"><span class="toc-number">1.2.</span> <span class="toc-text">故障原因</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E6%95%85%E9%9A%9C%E5%A4%84%E7%90%86"><span class="toc-number">1.3.</span> <span class="toc-text">故障处理</span></a></li></ol></li><li class="toc-item toc-level-2"><a class="toc-link" href="#Bug-%E5%A4%8D%E7%8E%B0"><span class="toc-number">2.</span> <span class="toc-text">Bug 复现</span></a></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E6%BA%90%E7%A0%81%E5%89%96%E6%9E%90"><span class="toc-number">3.</span> <span class="toc-text">源码剖析</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%91%BD%E4%BB%A4%E8%A7%A3%E6%9E%90%E6%B5%81%E7%A8%8B"><span class="toc-number">3.1.</span> <span class="toc-text">命令解析流程</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E5%BC%82%E5%B8%B8%E6%8A%9B%E5%87%BA%E4%BD%8D%E7%BD%AE"><span class="toc-number">3.2.</span> <span class="toc-text">异常抛出位置</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E6%95%B0%E6%8D%AE%E9%94%99%E4%B9%B1%E5%8E%9F%E5%9B%A0"><span class="toc-number">3.3.</span> <span class="toc-text">数据错乱原因</span></a></li></ol></li><li class="toc-item toc-level-2"><a class="toc-link" href="#Bug-%E4%BF%AE%E5%A4%8D"><span class="toc-number">4.</span> <span class="toc-text">Bug 修复</span></a><ol class="toc-child"><li class="toc-item toc-level-3"><a class="toc-link" href="#%E9%94%99%E8%AF%AF%E7%9A%84%E4%BF%AE%E5%A4%8D%E6%96%B9%E6%A1%88"><span class="toc-number">4.1.</span> <span class="toc-text">错误的修复方案</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E7%A8%B3%E5%AE%9A%E5%A4%8D%E7%8E%B0%E4%B8%8E%E6%94%B9%E8%BF%9B"><span class="toc-number">4.2.</span> <span class="toc-text">稳定复现与改进</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E8%83%8C%E6%99%AF%E4%B8%8E%E6%9C%80%E7%BB%88%E4%BF%AE%E5%A4%8D"><span class="toc-number">4.3.</span> <span class="toc-text">背景与最终修复</span></a></li><li class="toc-item toc-level-3"><a class="toc-link" href="#%E6%9C%80%E7%BB%88%E7%9A%84%E9%AA%8C%E8%AF%81%E8%BF%87%E7%A8%8B"><span class="toc-number">4.4.</span> <span class="toc-text">最终的验证过程</span></a></li></ol></li><li class="toc-item toc-level-2"><a class="toc-link" href="#%E7%AE%80%E5%8D%95%E6%80%BB%E7%BB%93"><span class="toc-number">5.</span> <span class="toc-text">简单总结</span></a></li></ol></ul></div></div></div><div class="pure-u-1 pure-u-md-3-4"><div id="footer">Copyright © 2024 <a href="/." rel="nofollow">Just For Fun.</a> Powered by<a rel="nofollow" target="_blank" href="https://hexo.io"> Hexo.</a><a rel="nofollow" target="_blank" href="https://github.com/selfboot/maupassant-hexo"> Theme</a> by<a rel="nofollow" target="_blank" href="https://github.com/selfboot"> SelfBoot.</a><p><span id="busuanzi_container_site_pv"></span>本站总访问量<span id="busuanzi_value_site_pv"></span>次，<span id="busuanzi_container_site_uv"></span>本站访客数<span id="busuanzi_value_site_uv"></span>人次</p></div></div></div><link rel="stylesheet" type="text/css" href="/css/donate.css"><link rel="stylesheet" type="text/css" href="/css/copyright.css"><a class="show" id="rocket" href="#top" aria-label="Back to top"></a><script type="text/javascript" src="/js/totop.js?v=1.0.0" async=""></script><script type="text/javascript" src="/js/jquery.fancybox.min.js" defer=""></script><script type="text/javascript" src="/js/fancybox.js?v=1.0.0" defer=""></script><link rel="stylesheet" type="text/css" href="/css/jquery.fancybox.min.css"><script type="text/javascript" src="/js/toc.js?v=1.0.0"></script><script type="text/javascript" src="/js/codeblock-resizer.js?v=1.0.0"></script><script type="text/javascript" src="/js/smartresize.js?v=1.0.0"></script></div></body></html>